package com.ingramcontent.model;

import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;

import org.w3c.dom.ls.LSInput;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LSInputImpl implements java.io.Serializable, LSInput {

    static final long serialVersionUID = 1L;
    
    private Reader characterStream;
    private InputStream byteStream;
    private String stringData;
    private String systemId;
    private String publicId;
    private String baseURI;
    private String encoding;
    private boolean certifiedText;
    
    public LSInputImpl() {
    }
    
	public Reader getCharacterStream() {
		return characterStream;
	}
	public void setCharacterStream(Reader characterStream) {
		this.characterStream = characterStream;
	}
	public InputStream getByteStream() {
		return byteStream;
	}
	public void setByteStream(InputStream byteStream) {
		this.byteStream = byteStream;
	}
	public String getStringData() {
		  synchronized (byteStream) {
		        try {
		            byte[] input = new byte[byteStream.available()];
		            String contents = new String(input);
		            return contents;
		        } catch (IOException e) {
		            e.printStackTrace();
		            System.out.println("Exception " + e);
		            return null;
		        }
		    }
	}
	public void setStringData(String stringData) {
		this.stringData = stringData;
	}
	public String getSystemId() {
		return systemId;
	}
	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}
	public String getPublicId() {
		return publicId;
	}
	public void setPublicId(String publicId) {
		this.publicId = publicId;
	}
	public String getBaseURI() {
		return baseURI;
	}
	public void setBaseURI(String baseURI) {
		this.baseURI = baseURI;
	}
	public String getEncoding() {
		return encoding;
	}
	public void setEncoding(String encoding) {
		this.encoding = encoding;
	}
	public boolean isCertifiedText() {
		return certifiedText;
	}
	public void setCertifiedText(boolean certifiedText) {
		this.certifiedText = certifiedText;
	}
	public boolean getCertifiedText() {
		return false;
	}


}