package com.ingramcontent.validator;

import java.io.InputStream;

import org.w3c.dom.ls.LSInput;
import org.w3c.dom.ls.LSResourceResolver;

import com.ingramcontent.model.LSInputImpl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClasspathResourceResolver implements java.io.Serializable, LSResourceResolver {

    static final long serialVersionUID = 1L;

    public ClasspathResourceResolver() {
    }


    @Override
    public LSInput resolveResource(String type, String namespaceURI, String publicId, String systemId, String baseURI) {
        LSInputImpl input = new LSInputImpl();
        InputStream stream = getClass().getClassLoader().getResourceAsStream(systemId);
        input.setPublicId(publicId);
        input.setSystemId(systemId);
        input.setBaseURI(baseURI);
        input.setByteStream(stream);
        return input;
    }

}