package com.ingramcontent.validator;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.StringReader;

import javax.xml.XMLConstants;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import javax.xml.validation.Validator;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XMLValidator implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public XMLValidator() {
    }

    public static String ERROR_MSG = null;
	
	public static boolean validateXMLSchema(String schemaData, String xmlData) {
	    ERROR_MSG = null;
		try {
			SchemaFactory factory = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
			factory.setResourceResolver(new ClasspathResourceResolver());
			Schema schema = factory.newSchema(new StreamSource(new StringReader(schemaData)));
			Validator validator = schema.newValidator();
			validator.validate(new StreamSource(new StringReader(xmlData)));
		} catch (Exception e) {
			ERROR_MSG =  e.getMessage();
			return false;
		}
		return true;
	}

}